<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * @file
 * Primary module hooks for MyAcademicID user fields module.
 */

/**
 * Implements hook_entity_base_field_info().
 */
function myacademicid_user_fields_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'user') {
    $service = \Drupal::service('myacademicid_user_fields');
    return $service->attachBaseFields();
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function myacademicid_user_fields_user_presave(EntityInterface $user) {
  $service = \Drupal::service('myacademicid_user_fields');
  $service->checkFieldChange($user);
}
