myacademicid_user_claims.settings:
  type: config_object
  label: 'MyAcademicID user claims settings'
  mapping:
    assert_member:
      type: sequence
      label: 'Additional member assertions'
      constraints:
        FullyValidatable: ~
      sequence:
        type: string
        constraints:
          Regex: '/^[a-zA-Z\-_]+$/'
