myacademicid_user_fields.settings:
  type: config_object
  label: 'MyAcademicID user fields settings'
  mapping:
    mode:
      type: string
      label: 'Mode'
      constraints:
        Choice:
          - client
          - server

myacademicid_user_fields.types:
  type: config_object
  label: 'MyAcademicID affiliation types'
  mapping:
    additional:
      type: sequence
      label: 'Additional affiliation types'
      constraints:
        FullyValidatable: ~
      sequence:
        type: string
        constraints:
          Regex: '/^[a-zA-Z\-_]+(\|.*)?$/'
