<?php

/**
 * @file
 * Primary module hooks for MyAcademicID user claims module.
 */

use Drupal\user\UserInterface;

/**
 * Implements hook_oauth2_server_user_claims.
 *
 * @return array
 *   An array of additional claims.
 */
function myacademicid_user_claims_oauth2_server_user_claims(UserInterface $account, array $requested_scopes) {
  $assertion = \Drupal::service('myacademicid_user_claims.assertion');
  return $assertion->userClaims($account, $requested_scopes);
}
