myacademicid_user_hei.settings:
  type: config_object
  label: 'MyAcademicID user institution settings'
  mapping:
    sync_mode:
      type: string
      label: 'Synchronization mode'
      constraints:
        Choice:
          - 'sync'
          - 'empty'
          - 'nosync'
    import:
      type: boolean
      label: 'Lookup and import'
