myacademicid_user_roles.affilliation_to_role:
  type: config_object
  label: 'Affilliation mapping'
  mapping:
    affilliation_mapping:
      type: mapping
      label: 'Affilliation types'
      mapping:
        role:
          type: string
          label: 'Role'

myacademicid_user_roles.role_to_affilliation:
  type: config_object
  label: 'Role mapping'
  mapping:
    role_mapping:
      type: mapping
      label: 'Roles'
      mapping:
        affilliation:
          type: string
          label: 'Affilliation type'
