myacademicid_user_roles.affiliation_to_role:
  type: config_object
  label: 'Affiliation mapping'
  mapping:
    affiliation_mapping:
      type: sequence
      label: 'Affiliation types'
      sequence:
        type: string

myacademicid_user_roles.role_to_affiliation:
  type: config_object
  label: 'Role mapping'
  mapping:
    role_mapping:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
